### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by lastnamelava** [rstacruz/jquery.transit#223]
Hey man, I was planning on showing off your awesome website to my coworkers, but ricostacruz.com appears to need a rewewal

**Comment by qsysmine** [comment]
Second on this:
![screen shot 2015-03-26 at 8 44 50 pm](https://cloud.githubusercontent.com/assets/4681886/6861766/0a9764f0-d3f9-11e4-9779-8e3f11aee549.png)

**Comment by qsysmine** [comment]
The issue has been resolved, please close.

**Comment by rstacruz** [comment]
sorry about that... yes, i just fixed this right this instant ;)
